Users route
dsckiet/website-backend-v2 pull request #50
Opened 2021-04-19 18:28 UTC by priyanshu20

2021-04-19 19:15 UTC, ritiksr25 commented on controllers/users_controller.js
> +			{ role: { $in: role } },
in this route,
- filter with showOnWebsite: true
- select fields name, email, designation, role, github, linkedin, twitter, portfolio, image

2021-04-19 21:00 UTC, ritiksr25 requested changes

2021-04-21 10:07 UTC, priyanshu20 commented
@ritiksr25

2021-04-21 10:08 UTC, ritiksr25 approved these changes
naice:)

2021-04-21 10:08 UTC, merged